---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- name: mutating-pod-webhook.kb.io
  clientConfig:
    service:
      name: webhook-service
      namespace: my-computeclass-system
      path: /mutate-core-v1-pod # webhook endpoint
  admissionReviewVersions:
  - v1
  failurePolicy: Fail
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations:
    - CREATE
    resources:
    - pods # check for pods
  namespaceSelector: # exclude namespace
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values: ["my-computeclass-system"]
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: my-computeclass-system
      path: /validate-scaling-tryu-com-v1-mycomputeclass
  failurePolicy: Fail
  name: vmycomputeclass-v1.kb.io
  rules:
  - apiGroups:
    - scaling.tryu.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mycomputeclasses
  sideEffects: None
