namespace: my-computeclass-system

resources:
  - certificate.yaml

configMapGenerator:
  - name: my-computeclass-config
    literals:
      - SERVICE_NAME=my-computeclass-webhook-service
      - SERVICE_NAMESPACE=my-computeclass-system
